version: '3.8'

services:
  spotify-tracker:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_SECRET_KEY=your-development-secret-key
      - ADMIN_PASSWORD=admin123
      - SPOTIPY_CLIENT_ID=${SPOTIPY_CLIENT_ID}
      - SPOTIPY_CLIENT_SECRET=${SPOTIPY_CLIENT_SECRET}
      - SPOTIPY_REDIRECT_URI=http://localhost:8080/admin/callback
      - FLASK_DEBUG=false
      - LOG_LEVEL=INFO
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
      # Mount logs for debugging
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
