name: Deploy to Railway

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd webapp
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run basic tests
      run: |
        cd webapp
        python -c "import app; print('✅ App imports successfully')"
        python -c "from app.config import Config; Config.validate() if hasattr(Config, 'validate') else print('✅ Config loads successfully')"
    
    - name: Check for syntax errors
      run: |
        python -m py_compile webapp/app.py
        find webapp -name "*.py" -exec python -m py_compile {} \;

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Railway CLI
      run: |
        curl -fsSL https://railway.app/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Deploy to Railway
      run: |
        railway login --token ${{ secrets.RAILWAY_TOKEN }}
        railway up --service ${{ secrets.RAILWAY_SERVICE_NAME }}
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
